# Environments test

name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: main
      url: ${{ steps.deploy.outputs.site_url }} # the URL generated in the deploy step. This can come from your hosting provider or be a static URL.

    steps:
      # "Deploy site" and set output for URL
      - name: deploy
        id: deploy
        run: |
          echo "::set-output name=site_url::https://github.com/lannonbr/"
